# vim: set ft=ansible:
---
- name: Workshop users
  hosts: localhost
  become: yes
  vars_files:
    - "{{config}}_vars.yml"
  tasks:

  - name: 'Add {{ user_prefix }}{{user}} to htpasswd file'
    command: "htpasswd -b /etc/origin/master/htpasswd {{ user_prefix }}{{ user }} {{default_password}}"

  - name: 'Check for explore-{{user}} project'
    command: "oc get project explore-{{user}}"
    register: project_out
    ignore_errors: true

  - name: 'Create explore-{{user}} project'
    command: "oc new-project explore-{{user}} --as={{ user_prefix }}{{user}} --skip-config-write"
    when: project_out | failed

  - name: 'Check for {{ user_prefix }}{{user}} in GitLab'
    uri:
      url: 'http://gitlab-ce.workshop-infra.svc.cluster.local/api/v3/users?username={{ user_prefix }}{{user}}'
      HEADER_PRIVATE-TOKEN: "{{root_token}}"
      method: GET
      status_code: 200
      return_content: yes
    register: user_result
    ignore_errors: true

  - name: 'Create {{ user_prefix }}{{user}} in GitLab'
    uri:
      url: 'http://{{gitlab_hostname}}/api/v3/users'
      HEADER_PRIVATE-TOKEN: "{{root_token}}"
      body: 'confirm=false&email={{ user_prefix }}{{user}}@example.com&username={{ user_prefix }}{{user}}&name={{ user_prefix }}{{user}}&password={{default_password}}'
      method: POST
      status_code: 201
      return_content: no
    register: result
    until: result|success
    retries: 3
    delay: 60
    when: 'user_result.json == []'

  - name: 'Get {{ user_prefix }}{{user}} token'
    uri:
      url: 'http://{{gitlab_hostname}}/api/v3/session'
      body: 'login={{ user_prefix }}{{user}}&password={{default_password}}'
      method: POST
      status_code: 201
    register: token_out
    until: token_out|success
    retries: 3
    delay: 60

  - name: 'Check if {{ user_prefix }}{{user}} project exists'
    uri:
      url: 'http://{{gitlab_hostname}}/api/v3/projects/{{ user_prefix }}{{user}}%2Fnationalparks'
      HEADER_PRIVATE-TOKEN: "{{token_out.json.private_token}}"
      method: GET
      status_code: 404
      return_content: no
    register: project_absent
    ignore_errors: true

  - name: 'Import nationalparks repository for {{ user_prefix }}{{user}}'
    uri:
      url: 'http://{{gitlab_hostname}}/api/v3/projects'
      HEADER_PRIVATE-TOKEN: "{{token_out.json.private_token}}"
      body: 'name=nationalparks&import_url=https://github.com/openshift-roadshow/nationalparks&public=true'
      method: POST
      status_code: 201
      return_content: no
    register: result
    until: result|success
    retries: 3
    delay: 60
    when: project_absent | success
